stages:
  - build
  - deploy

build-package:
  stage: build
  image: maven:3-jdk-8
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar

deploy-heroku:
  stage: deploy
  image: ubuntu:latest
  variables:
    HEROKU_API_KEY: $HEROKU_API_KEY
  script:
    - apt-get update
    - apt-get install openjdk-8-jdk-headless -y
    - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
    - heroku plugins:install heroku-cli-deploy
    - heroku deploy:jar target/*jar --app $HEROKU_APP_NAME
